version: 2
jobs:
  build:
    docker:
      - image: awav/tensorflow:2.0-preview

    steps:
      - checkout
      - run:
          name: Install GPflow
          command: |
            pip install -U pip
            pip install git+git://github.com/GPflow/GPflow.git
            pip install -r tests_requirements.txt
      - run:
          name: Make notebooks
          command: |
            jupytext --execute --to notebook -o notebooks/intro_to_gpflow2.ipynb notebooks/intro_to_gpflow2.pct.py
      - run: echo "Notebooks created"
