version: 2
jobs:
  build:
    docker:
      - image: awav/tensorflow:2.0-preview

    steps:
      - checkout
      - run:
          name: Make notebooks
          command: |
           echo Hello World >> test.txt
           git add test.txt
           git commit -m "Test commit from Circle CI"
           git push origin vincent/setup-build
      - run: echo "Notebooks created"
